name: fetch
on: [push]
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - run: curl -sI https://downloads.openwrt.org/releases/24.10.0/targets/mediatek/filogic/openwrt-sdk-24.10.0-mediatek-filogic_gcc-13.3.0_musl.Linux-x86_64.tar.xz
